server:
  port: 8085

spring:
  application:
    name: trade-history-service
  datasource:
    url: jdbc:sqlite:/data/trade.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
